In [5]:
import numpy as np

In [7]:

T_73 = np.array([[-0.11786941, -0.03269680, 0.99249067, 0.06784734], [-0.43999276, -0.89427568, -0.08171527, 0.15231394], [0.89023209, -0.44632044, 0.09102140, 0.98849771], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
p_3 = np.array([[0.33653722], [0.61483691], [0.36347208],[1]])
print(T_73@p_3)

In [13]:
p_0 = np.array([[0.49950814], [-0.99167920], [0.53100593]])
R_70 = np.array([[0.00677526, -0.02112198, -0.99975395], [0.98900088, 0.14786633, 0.00357839], [0.14775437, -0.98878178, 0.02189149]])
q_0 = np.array([[0.54959041], [-0.73259071], [-0.54154884]])

# Find q in the coordinates of frame 0:
print(R_70@q_0 + p_0)

[[ 1.06012112]
 [-0.55839717]
 [ 1.32472735]]


In [16]:
theta = 2.58

# find rotation matrix R_01 if Suppose that frame 1 and frame 0 are initially aligned, and that frame 1 rotates by an angle 2.58 about the y-axis.

R_01 = np.array([[np.cos(theta), 0, np.sin(theta)], [0, 1, 0], [-np.sin(theta), 0, np.cos(theta)]])
print(R_01)


[[-0.84640804  0.          0.53253491]
 [ 0.          1.          0.        ]
 [-0.53253491  0.         -0.84640804]]


In [19]:
# he pose of frame 2 in the coordinates of frame 5 is:
T_52 = np.array([[0.41787433, 0.90788909, -0.03344300, 0.82147101], [0.59151379, -0.24394752, 0.76850572, 0.54395600], [0.68955962, -0.34092081, -0.63896833, 0.56663051], [0.00000000, 0.00000000, 0.00000000, 1.00000000]])
# Find the pose of frame 5 in the coordinates of frame 2:
np.linalg.inv(T_52)

array([[ 0.41787434,  0.5915138 ,  0.68955963, -1.05575465],
       [ 0.9078891 , -0.24394752, -0.34092081, -0.41993172],
       [-0.033443  ,  0.76850572, -0.63896833, -0.02850189],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])